### ISSUE TITLE
I got some issue. Help me to fix!

### ISSUE THREAD

**Issue by emmu123** [vsl-dev/status-page#1]
```node index.js
[System Manager]: System running on port 8080
[System Manager]: https://github.com/vsl-dev
TypeError: /home/runner/status-page/web/views/index.ejs:56
    54| 
    55| <div class="container" style="padding: 0 0 0 20px;">
 >> 56| <% log.fetch(`${x.link_id}`).slice(-46).reverse().forEach((a) => { %>
    57| <% if((a.error == true) == false) { %>
    58| <% if(a.status_code == 200) { %><div style="background-color: green;" class="status tooltip"><span class="tooltiptext">Status: Online!<br><span style="font-size: 0.5em;">Last Control: <%= moment(a.last_req).from() %></span></span></div><% } else { %><div style="background-color: red;" class="status tooltip"><span class="tooltiptext">Status: Offline!<br><span style="font-size: 0.5em;">Last Control: <%= moment(a.last_req).from() %></span></span></div><% }} else { %>
    59| <div style="background-color: orange;" class="status tooltip"><span class="tooltiptext">Status: Degraded!<br><span style="font-size: 0.5em;">Last Control: <%= moment(a.last_req).from() %></span></span></div>

Cannot read properties of null (reading 'slice')
    at eval ("/home/runner/status-page/web/views/index.ejs":49:33)
    at Array.forEach (<anonymous>)
    at eval ("/home/runner/status-page/web/views/index.ejs":12:12)
    at index (/home/runner/status-page/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/home/runner/status-page/node_modules/ejs/lib/ejs.js:274:36)
    at View.exports.renderFile [as engine] (/home/runner/status-page/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/home/runner/status-page/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/status-page/node_modules/express/lib/application.js:657:10)
    at Function.render (/home/runner/status-page/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/home/runner/status-page/node_modules/express/lib/response.js:1039:7)
TypeError: /home/runner/status-page/web/views/index.ejs:56
    54| 
    55| <div class="container" style="padding: 0 0 0 20px;">
 >> 56| <% log.fetch(`${x.link_id}`).slice(-46).reverse().forEach((a) => { %>
    57| <% if((a.error == true) == false) { %>
    58| <% if(a.status_code == 200) { %><div style="background-color: green;" class="status tooltip"><span class="tooltiptext">Status: Online!<br><span style="font-size: 0.5em;">Last Control: <%= moment(a.last_req).from() %></span></span></div><% } else { %><div style="background-color: red;" class="status tooltip"><span class="tooltiptext">Status: Offline!<br><span style="font-size: 0.5em;">Last Control: <%= moment(a.last_req).from() %></span></span></div><% }} else { %>
    59| <div style="background-color: orange;" class="status tooltip"><span class="tooltiptext">Status: Degraded!<br><span style="font-size: 0.5em;">Last Control: <%= moment(a.last_req).from() %></span></span></div>

Cannot read properties of null (reading 'slice')
    at eval ("/home/runner/status-page/web/views/index.ejs":49:33)
    at Array.forEach (<anonymous>)
    at eval ("/home/runner/status-page/web/views/index.ejs":12:12)
    at index (/home/runner/status-page/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/home/runner/status-page/node_modules/ejs/lib/ejs.js:274:36)
    at View.exports.renderFile [as engine] (/home/runner/status-page/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/home/runner/status-page/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/status-page/node_modules/express/lib/application.js:657:10)
    at Function.render (/home/runner/status-page/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/home/runner/status-page/node_modules/express/lib/response.js:1039:7)
```

This is the error

**Comment by emmu123** [comment]
I fixed.
Thank you this src.
